name: ristretto255
description: A tiny cup, a mighty punch - ristretto255!!
version: 1.0.2
repository: https://github.com/justkawal/ristretto255

environment:
  sdk: ^3.0.5

dependencies:
  collection: ^1.18.0
  cryptography: ^2.7.0
  edwards25519: ^1.0.4

dev_dependencies:
  convert: ^3.1.1
  lints: ^3.0.0
  test: ^1.21.0
